/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Nick Emanuel Salcedo Alfaro
 */
public class PnlCompraEntradas extends javax.swing.JPanel {

    /**
     * Creates new form CompraDeEntradasMenu
     */
    public PnlCompraEntradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblZonaSeleccionada = new javax.swing.JLabel();
        LblCompraEntrada = new javax.swing.JLabel();
        LblTotalAPagar = new javax.swing.JLabel();
        LblZona = new javax.swing.JLabel();
        LblPrecioUnitario = new javax.swing.JLabel();
        TxtTarjeta = new javax.swing.JTextField();
        LblPrecioUnitario2 = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();
        LblCantidadDeEntradas = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        BtnPagar = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(400, 620));
        setMinimumSize(new java.awt.Dimension(400, 620));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 620));

        LblZonaSeleccionada.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblZonaSeleccionada.setText("Zona seleccionada:");
        LblZonaSeleccionada.setMaximumSize(new java.awt.Dimension(148, 22));
        LblZonaSeleccionada.setMinimumSize(new java.awt.Dimension(148, 22));
        LblZonaSeleccionada.setPreferredSize(new java.awt.Dimension(148, 22));

        LblCompraEntrada.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblCompraEntrada.setText("Compra de Entradas");
        LblCompraEntrada.setMaximumSize(new java.awt.Dimension(148, 22));
        LblCompraEntrada.setMinimumSize(new java.awt.Dimension(148, 22));
        LblCompraEntrada.setPreferredSize(new java.awt.Dimension(148, 22));

        LblTotalAPagar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblTotalAPagar.setText("<html> <head>   <style>     div {       margin: 10px; /* Espacio alrededor del elemento div */     }   </style> </head> <body>   <div>    Total a pagar: <br> total </div> </body> </html>");
        LblTotalAPagar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LblTotalAPagar.setMaximumSize(new java.awt.Dimension(148, 22));
        LblTotalAPagar.setMinimumSize(new java.awt.Dimension(148, 22));
        LblTotalAPagar.setOpaque(true);
        LblTotalAPagar.setPreferredSize(new java.awt.Dimension(148, 22));

        LblPrecioUnitario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblPrecioUnitario.setText("Precio Unitario:");
        LblPrecioUnitario.setMaximumSize(new java.awt.Dimension(148, 22));
        LblPrecioUnitario.setMinimumSize(new java.awt.Dimension(148, 22));
        LblPrecioUnitario.setPreferredSize(new java.awt.Dimension(148, 22));

        TxtTarjeta.setPreferredSize(new java.awt.Dimension(74, 35));
        TxtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTarjetaActionPerformed(evt);
            }
        });

        LblPrecioUnitario2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblPrecioUnitario2.setText("Tarjeta:");
        LblPrecioUnitario2.setMaximumSize(new java.awt.Dimension(148, 22));
        LblPrecioUnitario2.setMinimumSize(new java.awt.Dimension(148, 22));
        LblPrecioUnitario2.setPreferredSize(new java.awt.Dimension(148, 22));

        LblCantidadDeEntradas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblCantidadDeEntradas.setText("Cantidad de entradas:");
        LblCantidadDeEntradas.setMaximumSize(new java.awt.Dimension(148, 22));
        LblCantidadDeEntradas.setMinimumSize(new java.awt.Dimension(148, 22));
        LblCantidadDeEntradas.setPreferredSize(new java.awt.Dimension(148, 22));

        TxtCantidad.setPreferredSize(new java.awt.Dimension(74, 35));
        TxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadActionPerformed(evt);
            }
        });

        BtnPagar.setText("Pagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(BtnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LblTotalAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(LblPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblCantidadDeEntradas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPrecioUnitario2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LblCompraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblZonaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LblZona, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TxtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(TxtTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LblCompraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblZonaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblZona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(LblCantidadDeEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LblPrecioUnitario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TxtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(BtnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTarjetaActionPerformed

    private void TxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPagar;
    private javax.swing.JLabel LblCantidadDeEntradas;
    private javax.swing.JLabel LblCompraEntrada;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblPrecioUnitario;
    private javax.swing.JLabel LblPrecioUnitario2;
    private javax.swing.JLabel LblTotalAPagar;
    private javax.swing.JLabel LblZona;
    private javax.swing.JLabel LblZonaSeleccionada;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtTarjeta;
    // End of variables declaration//GEN-END:variables
}
