/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author ALGS
 */
public class PnlConciertos extends javax.swing.JPanel {

    /**
     * Creates new form conciertos
     */
    public PnlConciertos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnComprarEntradas = new javax.swing.JButton();
        BtnVerEntradas = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(450, 620));
        setPreferredSize(new java.awt.Dimension(450, 620));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");
        jLabel1.setToolTipText("");

        BtnComprarEntradas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnComprarEntradas.setText("<html><center><b>Comprar entradas</b></center><br>Adquiere nuevas entradas</html>");
        BtnComprarEntradas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 2, true));
        BtnComprarEntradas.setMinimumSize(new java.awt.Dimension(325, 135));
        BtnComprarEntradas.setPreferredSize(new java.awt.Dimension(325, 135));
        BtnComprarEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarEntradasActionPerformed(evt);
            }
        });

        BtnVerEntradas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnVerEntradas.setText("<html><center><b>Mis entradas</b></center><br>Ver entradas compradas</html>");
        BtnVerEntradas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 2, true));
        BtnVerEntradas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnVerEntradas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVerEntradas.setPreferredSize(new java.awt.Dimension(325, 135));
        BtnVerEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerEntradasActionPerformed(evt);
            }
        });

        BtnCerrarSesion.setBackground(new java.awt.Color(255, 102, 102));
        BtnCerrarSesion.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setText("Cerrar Sesión");
        BtnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        BtnCerrarSesion.setPreferredSize(new java.awt.Dimension(325, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnVerEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnComprarEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(BtnComprarEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(BtnVerEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnComprarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnComprarEntradasActionPerformed

    private void BtnVerEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVerEntradasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCerrarSesion;
    public javax.swing.JButton BtnComprarEntradas;
    public javax.swing.JButton BtnVerEntradas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
