/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Nick Emanuel Salcedo Alfaro
 */
public class PnlMisEntradas extends javax.swing.JPanel {

    /**
     * Creates new form MisEntradasMenu
     */
    public PnlMisEntradas() {
        setSize(450, 620);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        LblHist1 = new javax.swing.JLabel();
        LblHist4 = new javax.swing.JLabel();
        LblHist3 = new javax.swing.JLabel();
        LblHist2 = new javax.swing.JLabel();
        LblRegresar = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 620));
        setMinimumSize(new java.awt.Dimension(400, 620));
        setPreferredSize(new java.awt.Dimension(450, 620));

        LblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblTitulo.setText("Mis Entradas");

        LblHist1.setBackground(new java.awt.Color(255, 255, 255));
        LblHist1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LblHist1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblHist1.setText("<html> <head>   <style>     div {    margin: 20px;  background: white; }   </style> </head> <body>   <div>     <b>Entrada:  Entrada</b><br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LblHist1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblHist4.setBackground(new java.awt.Color(255, 255, 255));
        LblHist4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LblHist4.setText("<html> <head>   <style>     div {   margin: 20px;   }   </style> </head> <body>   <div>     <b>Entrada: Entrada</b><br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LblHist3.setBackground(new java.awt.Color(255, 255, 255));
        LblHist3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LblHist3.setText("<html> <head>   <style>     div {  margin: 20px;  }   </style> </head> <body>   <div>     <b>Entrada: Entrada</b><br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LblHist2.setBackground(new java.awt.Color(255, 255, 255));
        LblHist2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LblHist2.setText("<html> <head>   <style>     div { margin: 20px; }   </style> </head> <body>   <div>     <b>Entrada: Entrada</b> <br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LblRegresar.setText("<html><u>Volver</u></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(LblTitulo)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LblHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(LblHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LblHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(LblHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LblHist1;
    public javax.swing.JLabel LblHist2;
    public javax.swing.JLabel LblHist3;
    private javax.swing.JLabel LblHist4;
    public javax.swing.JLabel LblRegresar;
    private javax.swing.JLabel LblTitulo;
    // End of variables declaration//GEN-END:variables
}
