/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Nick Emanuel Salcedo Alfaro
 */
public class PnlMisEntradas extends javax.swing.JPanel {

    /**
     * Creates new form MisEntradasMenu
     */
    public PnlMisEntradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        LblHist1 = new javax.swing.JLabel();
        LblHist4 = new javax.swing.JLabel();
        LblHist3 = new javax.swing.JLabel();
        LblHist2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 620));
        setMinimumSize(new java.awt.Dimension(400, 620));
        setPreferredSize(new java.awt.Dimension(400, 620));

        LblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblTitulo.setText("Mis Entradas");

        LblHist1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LblHist1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblHist1.setText("<html> <head>   <style>     div {       margin: 20px; /* Espacio alrededor del elemento div */     }   </style> </head> <body>   <div>     Entrada: Entrada<br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LblHist1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblHist4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LblHist4.setText("<html> <head>   <style>     div {       margin: 20px; /* Espacio alrededor del elemento div */     }   </style> </head> <body>   <div>     Entrada: Entrada<br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblHist3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LblHist3.setText("<html> <head>   <style>     div {       margin: 20px; /* Espacio alrededor del elemento div */     }   </style> </head> <body>   <div>     Entrada: Entrada<br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblHist2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LblHist2.setText("<html> <head>   <style>     div {       margin: 20px; /* Espacio alrededor del elemento div */     }   </style> </head> <body>   <div>     Entrada: Entrada<br>     Zona: Zona <br>     Estado: Estado   </div> </body> </html>");
        LblHist2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(LblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(LblHist1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(LblHist2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(LblHist3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(LblHist4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblHist1;
    private javax.swing.JLabel LblHist2;
    private javax.swing.JLabel LblHist3;
    private javax.swing.JLabel LblHist4;
    private javax.swing.JLabel LblTitulo;
    // End of variables declaration//GEN-END:variables
}
