/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author USUARIO
 */
public class PnlRegistrar extends javax.swing.JPanel {

    /**
     * Creates new form PnlInicioSesion
     */
    public PnlRegistrar() {
        setSize(450, 620);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNombre = new javax.swing.JTextField();
        TxtApellidos = new javax.swing.JTextField();
        TxtDni = new javax.swing.JTextField();
        TxtNumeroTarjeta = new javax.swing.JTextField();
        TxtFechaExpiracion = new javax.swing.JTextField();
        BtnCrearCuenta = new javax.swing.JButton();
        LblRegistroUsuario = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblDni = new javax.swing.JLabel();
        LblClave = new javax.swing.JLabel();
        LblNumeroTarjeta = new javax.swing.JLabel();
        LblApellidos = new javax.swing.JLabel();
        LblFechaExpiracion = new javax.swing.JLabel();
        TxtCvv = new javax.swing.JTextField();
        LblCvv = new javax.swing.JLabel();
        TxtClave = new javax.swing.JPasswordField();
        LblRegresar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(450, 620));

        BtnCrearCuenta.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        BtnCrearCuenta.setText("Crear Cuenta");

        LblRegistroUsuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblRegistroUsuario.setText("Registro de Usuario");

        LblNombre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblNombre.setText("Nombre:");

        LblDni.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblDni.setText("Dni:");

        LblClave.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblClave.setText("Contraseña:");

        LblNumeroTarjeta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblNumeroTarjeta.setText("Número de tarjeta:");

        LblApellidos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblApellidos.setText("Apellidos:");

        LblFechaExpiracion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblFechaExpiracion.setText("Fecha de expiración:");

        LblCvv.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblCvv.setText("CVV:");

        LblRegresar.setText("<html><u>Volver</u><html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNombre)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblDni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblClave, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblNumeroTarjeta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtNumeroTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblFechaExpiracion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtFechaExpiracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblCvv, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtCvv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnCrearCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LblApellidos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(LblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblRegistroUsuario)
                        .addGap(30, 30, 30)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblRegistroUsuario)
                    .addComponent(LblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblClave)
                .addGap(11, 11, 11)
                .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblNumeroTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFechaExpiracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblCvv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCrearCuenta;
    private javax.swing.JLabel LblApellidos;
    private javax.swing.JLabel LblClave;
    private javax.swing.JLabel LblCvv;
    private javax.swing.JLabel LblDni;
    private javax.swing.JLabel LblFechaExpiracion;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblNumeroTarjeta;
    private javax.swing.JLabel LblRegistroUsuario;
    public javax.swing.JLabel LblRegresar;
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JPasswordField TxtClave;
    private javax.swing.JTextField TxtCvv;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtFechaExpiracion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
