/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Gabriel
 */
public class PnlSeleccionZona extends javax.swing.JPanel {

    /**
     * Creates new form seleccionZona
     */
    public PnlSeleccionZona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblZonas = new javax.swing.JLabel();
        BtnZonaPreferencial = new javax.swing.JButton();
        BtnZonaGeneral = new javax.swing.JButton();
        BtnZonaVip = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 620));

        LblZonas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblZonas.setText("SELECCIONAR ZONA");

        BtnZonaPreferencial.setText("<html><center><b>ZONA PREFERENCIAL</b></center><br>Cantidad entradas: 200 | S/ 100</html>");
        BtnZonaPreferencial.setPreferredSize(new java.awt.Dimension(325, 90));

        BtnZonaGeneral.setText("<html><center><b>ZONA GENERAL</b></center><br>Cantidad entradas: 300 | S/ 50</html>");
        BtnZonaGeneral.setPreferredSize(new java.awt.Dimension(325, 90));

        BtnZonaVip.setText("<html><center><b>ZONA VIP</b></center><br>Cantidad entradas: 100 | S/ 150</html>");
        BtnZonaVip.setPreferredSize(new java.awt.Dimension(325, 90));
        BtnZonaVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnZonaVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(LblZonas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnZonaVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnZonaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnZonaPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LblZonas)
                .addGap(48, 48, 48)
                .addComponent(BtnZonaVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(BtnZonaPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(BtnZonaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("PnlNombre");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnZonaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnZonaVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnZonaVipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnZonaGeneral;
    private javax.swing.JButton BtnZonaPreferencial;
    private javax.swing.JButton BtnZonaVip;
    private javax.swing.JLabel LblZonas;
    // End of variables declaration//GEN-END:variables
}
