/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Gabriel
 */
public class verConciertos extends javax.swing.JPanel {

    /**
     * Creates new form verConciertos
     */
    public verConciertos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnNombre2 = new javax.swing.JButton();
        BtnNombre3 = new javax.swing.JButton();
        BtnNombre1 = new javax.swing.JButton();
        LblNombre = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 620));

        BtnNombre2.setText("CONCIERTO 2");
        BtnNombre2.setPreferredSize(new java.awt.Dimension(325, 90));
        BtnNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNombre2ActionPerformed(evt);
            }
        });

        BtnNombre3.setText("CONCIERTO 3");
        BtnNombre3.setPreferredSize(new java.awt.Dimension(325, 90));

        BtnNombre1.setText("CONCIERTO 1");
        BtnNombre1.setPreferredSize(new java.awt.Dimension(325, 90));
        BtnNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNombre1ActionPerformed(evt);
            }
        });

        LblNombre.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        LblNombre.setText("CONCIERTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblNombre)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(BtnNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(BtnNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(BtnNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        BtnNombre2.getAccessibleContext().setAccessibleName("BtnNombre2");
        BtnNombre3.getAccessibleContext().setAccessibleName("BtnNombre3");
        BtnNombre1.getAccessibleContext().setAccessibleName("BtnNombre1");
        LblNombre.getAccessibleContext().setAccessibleName("LblNombre");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNombre2ActionPerformed

    private void BtnNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNombre1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNombre1;
    private javax.swing.JButton BtnNombre2;
    private javax.swing.JButton BtnNombre3;
    private javax.swing.JLabel LblNombre;
    // End of variables declaration//GEN-END:variables
}
